### PR TITLE
Unlock importlib-metadata

### PR DESCRIPTION
**Pull request by nllong**

### CODE REVIEW

**Review by corymosiman12 — COMMENTED** [review]
Have you tested the develop branch of alfalfa-client on alfalfa to start / stop / advance / etc.? Is that something we should add in do you think?

**Comment by nllong** [comment]
Hmm, I tested the submit, start, advance, stop, but they failed because my FMU didn't work in alfalfa. I think we'll need to test more thoroughly.

**Comment by corymosiman12** [comment]
kk. just trying to think how to best make sure changes to the client are working as expected. Should we set up an integration test to pull from alfalfa develop, then test the client on it?

**Comment by nllong** [comment]
> kk. just trying to think how to best make sure changes to the client are working as expected. Should we set up an integration test to pull from alfalfa develop, then test the client on it?

that would be ideal, that is have this repo stand up an alfalfa instance then run its tests. Or vice versa, that is have alfalfa pull specific versions of alfalfa-client to test against.

**Comment by corymosiman12** [comment]
Dope. I think I will have this repo stand up the develop version of alfalfa. I can get that worked into gh-actions at some point soon.

**Comment by nllong** [comment]
> Dope. I think I will have this repo stand up the develop version of alfalfa. I can get that worked into gh-actions at some point soon.

sure, not highest of high priorities. I can test manually and let you know.

**Comment by nllong** [comment]
I've tested this with the https://github.com/NREL/alfalfa/tree/feat/add-poetry-update-deps branch. There were no issues after updating some of the FMU tests to pass datetime and the external_clock item shown below. 

```
tests/integration/test_refrig_case_osw.py::TestRefrigCaseOSW::test_simple_external_clock PASSED                                                        [ 14%]
tests/integration/test_refrig_case_osw.py::TestRefrigCaseOSW::test_simple_internal_clock PASSED                                                        [ 28%]
tests/integration/test_simple_fmu_control.py::TestSimpleFMUControl::test_control SKIPPED (unconditional skip)                                          [ 42%]
tests/integration/test_simple_thermostat_fmu.py::TestSimpleThermostat::test_io_with_external_clock PASSED                                              [ 57%]
tests/integration/test_single_zone_vav_fmu.py::TestSingleZoneVAVFMU::test_simple_internal_clock PASSED                                                 [ 71%]
tests/integration/test_small_office_osm.py::TestSmallOfficeOSM::test_simple_external_clock PASSED                                                      [ 85%]
tests/integration/test_small_office_osm.py::TestSmallOfficeOSM::test_simple_internal_clock PASSED                                                      [100%]

```

The only issue was the need to update the `.start` calls to pass booleans to the `external_clock` arg. This was not induced by my changes here.

```
alfalfa.start(
            model_id,
            external_clock=False,
            start_datetime=datetime.datetime(2019, 1, 2, 0, 0, 0),
            end_datetime=datetime.datetime(2019, 1, 3, 0, 0, 0),
            timescale=5
        )
```

**Comment by corymosiman12** [comment]
Hey Nick - you are right. I added type checking in this commit: https://github.com/NREL/alfalfa-client/commit/c79f645ca4d19742d3e207233ba912f5e9864469. I should probably add this to the CHANGELOG somewhere? I think I was waiting to see if we would come to a consensus on the `start_datetime` and `end_datetime` type checking (datetimes or ints/floats).

**Comment by nllong** [comment]
@corymosiman12 -- can we merge this down first and release it? Then I can update this PR: https://github.com/NREL/alfalfa/pull/132

**Pull request merged**
